CREATE TABLE trades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker TEXT NOT NULL,
    trade_type TEXT NOT NULL CHECK (trade_type IN ('LONG', 'SHORT')),
    entry_date DATE NOT NULL,
    entry_price NUMERIC(19,4) NOT NULL CHECK (entry_price > 0),
    exit_date DATE NOT NULL,
    exit_price NUMERIC(19,4) NOT NULL CHECK (exit_price > 0),
    number_of_shares NUMERIC(19,6) NOT NULL CHECK (number_of_shares > 0),
    CONSTRAINT trades_date_order CHECK (exit_date >= entry_date)
);

